### ISSUE TITLE
R version 4.4.0

### ISSUE THREAD

**Issue by FleurDamen** [cszang/treeclim#13]
Hi there,

I recently updated my Windows system to R version 4.4.0 and R studio version RStudio 2024.04.2+764 "Chocolate Cosmos". It seems as if the treeclim package is not compatible with this version of R. Are there plans to update treeclim or are there alternatives I can use?

Thanks!

**Comment by cszang** [comment]
Hi there,
sorry for any inconvencience. treeclim is currently not on CRAN due to some minor issues that need to be fixed. Hope to have it back on CRAN soon.
Best, Christian

**Comment by FleurDamen** [comment]
Hi Christian,

Thanks for letting me know, I really appreciate you building the package in the first place.
Any idea when it might be back on CRAN?

Thanks again!


Fleur Damen
PhD Candidate
Forestry | Forest Resources Management
The University of British Columbia | Vancouver Campus | Musqueam Traditional Territory
2424 Main Mall Room 2310 | Vancouver BC | V6T 1Z4 Canada
Phone 778 873 3139
***@***.******@***.***>

________________________________
