### ISSUE TITLE
Couple of issues

### ISSUE THREAD

**Issue by wkedziora** [cszang/treeclim#5]
I am new here so probably I do not know how to post that kind of stuff; anyway I would like to ask for some improvements.

My question is connected to seascorr. I have been using it in original MATLAB, but since I would love to see them here I have make some notes what I miss:
1. Can you make correlation y-axis scaled up to 1 all the time (maybe as an option)?
2. Can they be colored by user choice?
3. Can we add primary and secondary factors names in the graph?
4. Can we pick up two significance levels and show those numbers in the figure?
5. Can you add also Monte Carlo simulation?
6. Original version test stability in time (graph and statistical test) - can you add that?
7. Scatterplots for the most significant seasons
8. I would like to see a window in which we can compare original and model data?
9. I would love to add title to the plot.

Point me out how I can improve that question.

Best regards
Wojciech

**Comment by cszang** [comment]
Hi Wojciech! GitHub issues are not the place for general questions. If you have a question about treeclim, please ask on the mailing list <https://groups.google.com/forum/#!forum/treeclim>. Please make sure you have checked the FAQs <https://github.com/cszang/treeclim/wiki/FAQ> before asking your question! Closing this issue now. Cheers, Christian
