### ISSUE TITLE
Problem in loading library and dcc function

### ISSUE THREAD

**Issue by ithapa2** [cszang/treeclim#9]
Brief description of the problem
I have an error in loading library for treeclim. And the dcc function is not working. I had this problem since I installed new version of R studio.
```r
# insert reprex here
```
> library(treeclim)
Loading required package: Rcpp
Error: package or namespace load failed for ‘treeclim’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘zoo’
In addition: Warning message:
package ‘treeclim’ was built under R version 4.0.4

> out=dcc(chrono,spei3,selection =-6:9)
Error in dcc(chrono, spei3, selection = -6:9) : 
  could not find function "dcc"

**Comment by cszang** [comment]
Have you tried reinstalling treeclim including all dependencies?

**Comment by ithapa2** [comment]
I didn't get which dependencies it requires. I could successfully run it
before I updated R studio. I would just install treeclim and reshape 2 with
their libraries.

Thank you!

Regards,
Ichchha

**Comment by cszang** [comment]
Did you also update R? Just updating RStudio should not break anything. The easiest way to update all of your packages is via the packages dialog in RStudio.

**Comment by ithapa2** [comment]
Yes, I did!
Should I uninstall treeclim and again try installing it? I was concerned
about the warning message below and was wondering if the problem was with
4.0.4 version of R.
Loading required package: Rcpp
Error: package or namespace load failed for ‘treeclim’ in loadNamespace(i,
c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘zoo’
In addition: Warning message:
package ‘treeclim’ was built under R version 4.0.4

Thank you!

Regards,
Ichchha

**Comment by cszang** [comment]
Strange, treeclim does not depend on zoo. You could try uninstalling and reinstalling with deps. I am running treeclim on R 4.0.4 without trouble here.

**Comment by ithapa2** [comment]
Hello,
I had to upgrade Rtools going through the process listed here https://cran.r-project.org/bin/windows/Rtools/ followed by installing packages for Zoo, uninstalling, and reinstalling treeclim. The treeclim package finally worked.

**Comment by cszang** [comment]
Fine, closing now.
